### ISSUE TITLE
Mapa

### ISSUE THREAD

**Issue by nicolas7885** [MarkoVrljicak/algo3#2]
Cada Casillero debe tener espacio aereo y terrestre, se prueba poniendo una unidad aerea y terrestre en el mismo lugar, los terrenos aire no deben aceptar terrestres(osea que no te deje poner nada en la parte terrestre).
Poder preguntarle al mapa si hay un casillero en posicion x,y.
Cambiar en el constructo el nombre de las variables por ancho y alto, x y es muy feo..
El generador de mapa debe testear la distancia entre recursos y bases, y que los pedazos de aire no esten solitos por ahi, y cualquier otra condicion que tenga.
El generador de mapa debe ser configurable, al menos en tamaño, posiblemente en bases.

**Comment by MarkoVrljicak** [comment]
listo
